# Generated by Django 5.2.1 on 2025-05-11 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_progress_quiz_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='text',
        ),
    ]
