# Generated by Django 5.2.1 on 2025-05-22 10:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Course Description'),
        ),
    ]
