# Generated by Django 5.2.1 on 2025-05-22 10:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Lecture Description'),
        ),
    ]
