# Generated by Django 5.2.1 on 2025-05-15 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_lecture_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectureprogress',
            name='progress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.progress'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='completed_lectures',
            field=models.ManyToManyField(related_name='completed_in', through='courses.LectureProgress', to='courses.lecture'),
        ),
    ]
