# Generated by Django 5.2.1 on 2025-05-15 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lectureprogress_progress_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='completed_lectures',
        ),
    ]
