# Generated by Django 5.2.1 on 2025-05-15 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_progress_completed_lectures'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lectureprogress',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='progress',
            name='completed_lectures',
            field=models.ManyToManyField(through='courses.LectureProgress', to='courses.lecture'),
        ),
        migrations.AlterField(
            model_name='lectureprogress',
            name='progress',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.progress'),
        ),
        migrations.AlterUniqueTogether(
            name='lectureprogress',
            unique_together={('user', 'lecture', 'progress')},
        ),
    ]
