# Generated by Django 5.2.1 on 2025-05-15 11:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_lectureprogress_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lectureprogress',
            unique_together={('user', 'lecture')},
        ),
        migrations.AlterField(
            model_name='progress',
            name='completed_lectures',
            field=models.ManyToManyField(blank=True, to='courses.lecture'),
        ),
        migrations.RemoveField(
            model_name='lectureprogress',
            name='progress',
        ),
    ]
